# Generated by Django 5.0.3 on 2024-03-06 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicsCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[], max_length=10)),
                ('model_name', models.CharField(max_length=40, unique=True)),
                ('core_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gpu_base_clock', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
                ('gpu_max_clock', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[], max_length=10)),
                ('model_name', models.CharField(max_length=40, unique=True)),
                ('core_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('p_core_base_clock', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)])),
                ('p_core_max_clock', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0.1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='pc_builder.graphicscard')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='pc_builder.processor')),
            ],
        ),
    ]
