# Generated by Django 5.0.1 on 2024-02-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('team', models.CharField(choices=[('BOS', 'BOS'), ('MIA', 'MIA'), ('ORL', 'ORL'), ('CHI', 'CHI'), ('MIL', 'MIL'), ('PHI', 'PHI'), ('NYK', 'NYK'), ('LAL', 'LAL'), ('PHO', 'PHO'), ('GSW', 'GSW'), ('DEN', 'DEN'), ('SAC', 'SAC'), ('MIN', 'MIN'), ('DAL', 'DAL'), ('NOP', 'NOP')], max_length=50)),
                ('position', models.CharField(choices=[('G', 'G'), ('F', 'F'), ('C', 'C')], max_length=2)),
                ('ppg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rpg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('apg', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
