# Generated by Django 5.0.1 on 2024-02-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
